In [1]:
import pandas as pd
import numpy as np

print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)
print("Notebook is ready!")

Pandas version: 2.1.1
NumPy version: 1.26.0
Notebook is ready!

In [2]:
import pandas as pd
import numpy as np

# Load the datasets
movies = pd.read_csv("data/tmdb_5000_movies.csv")
credits = pd.read_csv("data/tmdb_5000_credits.csv")

# Display dataset dimensions
print("Movies dataset shape:", movies.shape)
print("Credits dataset shape:", credits.shape)

# Display first five rows
display(movies.head())
display(credits.head())

Movies dataset shape: (4803, 20)
Credits dataset shape: (4803, 4)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [3]:
print("Movies columns:")
print(movies.columns.tolist())

print("\nCredits columns:")
print(credits.columns.tolist())

Movies columns:
['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language', 'original_title', 'overview', 'popularity', 'production_companies', 'production_countries', 'release_date', 'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title', 'vote_average', 'vote_count']

Credits columns:
['movie_id', 'title', 'cast', 'crew']

In [4]:
print("Missing values in Movies:")
display(movies.isnull().sum().sort_values(ascending=False).head(10))

print("\nMissing values in Credits:")
display(credits.isnull().sum().sort_values(ascending=False).head(10))

Missing values in Movies:

homepage            3091
tagline              844
overview               3
runtime                2
release_date           1
budget                 0
vote_average           0
title                  0
status                 0
spoken_languages       0
dtype: int64

Missing values in Credits:

movie_id    0
title       0
cast        0
crew        0
dtype: int64

In [6]:
# Check duplicate records
print("Duplicate rows in movies:", movies.duplicated().sum())
print("Duplicate rows in credits:", credits.duplicated().sum())

# Check missing movie titles
print("Missing movie titles:", movies["title"].isnull().sum())
print("Missing credit titles:", credits["title"].isnull().sum())

Duplicate rows in movies: 0
Duplicate rows in credits: 0
Missing movie titles: 0
Missing credit titles: 0

In [7]:
# Select the columns needed for recommendations
movies_clean = movies[
    ["id", "title", "genres", "keywords", "overview"]
].copy()

# Fill missing overviews with empty strings
movies_clean["overview"] = movies_clean["overview"].fillna("")

# Remove rows without a movie title or ID
movies_clean = movies_clean.dropna(subset=["id", "title"])

print("Cleaned dataset shape:", movies_clean.shape)
display(movies_clean.head())

Cleaned dataset shape: (4803, 5)

,id,title,genres,keywords,overview
0,19995,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...
4,49529,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca..."

In [8]:
# Select the columns needed for recommendations
movies_clean = movies[
    ["id", "title", "genres", "keywords", "overview"]
].copy()

# Handle missing movie descriptions
movies_clean["overview"] = movies_clean["overview"].fillna("")

# Remove rows with missing IDs or titles
movies_clean = movies_clean.dropna(subset=["id", "title"])

# Display the results
print("Original movies shape:", movies.shape)
print("Cleaned movies shape:", movies_clean.shape)

display(movies_clean.head())

Original movies shape: (4803, 20)
Cleaned movies shape: (4803, 5)

,id,title,genres,keywords,overview
0,19995,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...
4,49529,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca..."

In [9]:
# Merge movie details with cast and crew information
movies_merged = movies_clean.merge(
    credits,
    left_on="id",
    right_on="movie_id",
    how="inner",
    suffixes=("_movie", "_credit")
)

print("Merged dataset shape:", movies_merged.shape)
print("\nColumns:")
print(movies_merged.columns.tolist())

display(movies_merged.head(3))

Merged dataset shape: (4803, 9)

Columns:
['id', 'title_movie', 'genres', 'keywords', 'overview', 'movie_id', 'title_credit', 'cast', 'crew']

,id,title_movie,genres,keywords,overview,movie_id,title_credit,cast,crew
0,19995,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...",19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...",285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."

In [10]:
print("Number of movies:", len(movies_merged))
print("Missing overviews:", movies_merged["overview"].isnull().sum())
print("Missing cast entries:", movies_merged["cast"].isnull().sum())
print("Missing crew entries:", movies_merged["crew"].isnull().sum())

display(
    movies_merged[
        ["title_movie", "genres", "keywords", "overview", "cast", "crew"]
    ].head(5)
)

Number of movies: 4803
Missing overviews: 0
Missing cast entries: 0
Missing crew entries: 0

,title_movie,genres,keywords,overview,cast,crew
0,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [11]:
import ast
import pandas as pd
import numpy as np

In [12]:
def convert(text):
    try:
        return ast.literal_eval(text) if isinstance(text, str) else []
    except (ValueError, SyntaxError):
        return []

In [13]:
def extract_names(obj):
    return [
        item["name"]
        for item in convert(obj)
        if isinstance(item, dict) and item.get("name")
    ]

movies_merged["genres_list"] = movies_merged["genres"].apply(extract_names)
movies_merged["keywords_list"] = movies_merged["keywords"].apply(extract_names)

display(
    movies_merged[
        ["title_movie", "genres_list", "keywords_list"]
    ].head(5)
)

,title_movie,genres_list,keywords_list
0,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon..."
1,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ..."
2,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi..."
3,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i..."
4,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel..."

In [14]:
def extract_cast(obj):
    return [
        item["name"]
        for item in convert(obj)[:3]
        if isinstance(item, dict) and item.get("name")
    ]

movies_merged["cast_list"] = movies_merged["cast"].apply(extract_cast)

display(
    movies_merged[["title_movie", "cast_list"]].head(5)
)

,title_movie,cast_list
0,Avatar,"[Sam Worthington, Zoe Saldana, Sigourney Weaver]"
1,Pirates of the Caribbean: At World's End,"[Johnny Depp, Orlando Bloom, Keira Knightley]"
2,Spectre,"[Daniel Craig, Christoph Waltz, Léa Seydoux]"
3,The Dark Knight Rises,"[Christian Bale, Michael Caine, Gary Oldman]"
4,John Carter,"[Taylor Kitsch, Lynn Collins, Samantha Morton]"

In [15]:
def extract_director(obj):
    return [
        item["name"]
        for item in convert(obj)
        if isinstance(item, dict)
        and item.get("job") == "Director"
        and item.get("name")
    ][:1]

movies_merged["director_list"] = movies_merged["crew"].apply(extract_director)

display(
    movies_merged[["title_movie", "director_list"]].head(5)
)

                                title_movie        director_list
0                                    Avatar      [James Cameron]
1  Pirates of the Caribbean: At World's End     [Gore Verbinski]
2                                   Spectre         [Sam Mendes]
3                     The Dark Knight Rises  [Christopher Nolan]
4                               John Carter     [Andrew Stanton]

In [16]:
# Keep only the useful features for recommendations
recommendation_data = movies_merged[
    [
        "id",
        "title_movie",
        "genres_list",
        "keywords_list",
        "cast_list",
        "director_list",
        "overview"
    ]
].copy()

# Replace missing overviews
recommendation_data["overview"] = (
    recommendation_data["overview"].fillna("")
)

# Convert text to lowercase and remove extra spaces
recommendation_data["overview"] = (
    recommendation_data["overview"]
    .astype(str)
    .str.lower()
    .str.strip()
)

print("Recommendation dataset shape:", recommendation_data.shape)
display(recommendation_data.head())

Recommendation dataset shape: (4803, 7)

,id,title_movie,genres_list,keywords_list,cast_list,director_list,overview
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski],"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes],a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan],following the death of district attorney harve...
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton],"john carter is a war-weary, former military ca..."

In [17]:
def combine_features(row):
    features = (
        row["genres_list"]
        + row["keywords_list"]
        + row["cast_list"]
        + row["director_list"]
    )

    # Normalize names and words
    features = [
        str(item).lower().replace(" ", "")
        for item in features
        if item
    ]

    overview = row["overview"]
    return " ".join(features) + " " + overview


recommendation_data["combined_features"] = (
    recommendation_data.apply(combine_features, axis=1)
)

display(
    recommendation_data[
        ["title_movie", "combined_features"]
    ].head(5)
)

,title_movie,combined_features
0,Avatar,action adventure fantasy sciencefiction cultur...
1,Pirates of the Caribbean: At World's End,adventure fantasy action ocean drugabuse exoti...
2,Spectre,action adventure crime spy basedonnovel secret...
3,The Dark Knight Rises,action crime drama thriller dccomics crimefigh...
4,John Carter,action adventure sciencefiction basedonnovel m...

In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

print("TF-IDF and cosine similarity imported successfully!")

TF-IDF and cosine similarity imported successfully!

In [19]:
# Create the TF-IDF vectorizer
tfidf = TfidfVectorizer(
    max_features=5000,
    stop_words="english"
)

# Convert combined movie features into vectors
tfidf_matrix = tfidf.fit_transform(
    recommendation_data["combined_features"].fillna("")
)

print("TF-IDF matrix shape:", tfidf_matrix.shape)
print("Number of movies:", len(recommendation_data))
print("Number of text features:", tfidf_matrix.shape[1])

TF-IDF matrix shape: (4803, 5000)
Number of movies: 4803
Number of text features: 5000

In [21]:
# Calculate cosine similarity between movie vectors
similarity_matrix = cosine_similarity(tfidf_matrix)

print("Similarity matrix shape:", similarity_matrix.shape)

Similarity matrix shape: (4803, 4803)

In [22]:
# Check similarity of the first movie with itself
print(
    "Similarity of the first movie with itself:",
    similarity_matrix[0, 0]
)

# Display similarity scores for the first movie
print("\nFirst five similarity scores:")
print(similarity_matrix[0][:5])

Similarity of the first movie with itself: 1.0000000000000002

First five similarity scores:
[1.         0.02250966 0.01253873 0.02128479 0.10696574]

In [23]:
# Create a mapping between movie titles and their indices
recommendation_data = recommendation_data.reset_index(drop=True)

indices = pd.Series(
    recommendation_data.index,
    index=recommendation_data["title_movie"].str.lower()
).drop_duplicates()


def recommend_movies(movie_title, top_n=5):
    movie_title = movie_title.strip().lower()

    if movie_title not in indices:
        print(f"Movie '{movie_title}' not found in the dataset.")
        return pd.DataFrame()

    idx = indices[movie_title]

    # Get similarity scores for the selected movie
    scores = list(enumerate(similarity_matrix[idx]))

    # Sort by similarity, excluding the selected movie itself
    scores = sorted(scores, key=lambda x: x[1], reverse=True)
    scores = [item for item in scores if item[0] != idx][:top_n]

    # Return recommended movie titles and similarity scores
    results = recommendation_data.iloc[[i[0] for i in scores]][
        ["title_movie"]
    ].copy()

    results["similarity_score"] = [round(i[1], 4) for i in scores]
    results = results.rename(columns={"title_movie": "recommended_movie"})

    return results.reset_index(drop=True)


print("Recommendation function created successfully!")

Recommendation function created successfully!

In [24]:
recommend_movies("The Dark Knight")

                         recommended_movie  similarity_score
0                    The Dark Knight Rises            0.4447
1                           Batman Returns            0.3714
2                            Batman Begins            0.3372
3  Batman: The Dark Knight Returns, Part 2            0.2955
4                           Batman Forever            0.2881

In [25]:
recommend_movies("Avatar")

         recommended_movie  similarity_score
0                   Aliens            0.2047
1            Falcon Rising            0.2037
2      Battle: Los Angeles            0.1976
3                Apollo 18            0.1841
4  Star Trek Into Darkness            0.1713

In [26]:
# Test with three different movies
test_movies = [
    "The Dark Knight",
    "Avatar",
    "Iron Man"
]

for movie in test_movies:
    print(f"\nRecommendations for: {movie}")
    display(recommend_movies(movie, top_n=5))

Recommendations for: The Dark Knight

                         recommended_movie  similarity_score
0                    The Dark Knight Rises            0.4447
1                           Batman Returns            0.3714
2                            Batman Begins            0.3372
3  Batman: The Dark Knight Returns, Part 2            0.2955
4                           Batman Forever            0.2881

Recommendations for: Avatar

         recommended_movie  similarity_score
0                   Aliens            0.2047
1            Falcon Rising            0.2037
2      Battle: Los Angeles            0.1976
3                Apollo 18            0.1841
4  Star Trek Into Darkness            0.1713

Recommendations for: Iron Man

            recommended_movie  similarity_score
0                  Iron Man 2            0.4445
1                  Iron Man 3            0.3568
2     Avengers: Age of Ultron            0.3289
3                     Ant-Man            0.2210
4  Captain America: Civil War            0.2203

In [27]:
# Check whether the selected movie appears in its own recommendations
movie_title = "The Dark Knight"

results = recommend_movies(movie_title, top_n=5)

if not results.empty:
    recommended_titles = results["recommended_movie"].str.lower().tolist()

    print("Number of recommendations:", len(results))
    print(
        "Selected movie excluded:",
        movie_title.lower() not in recommended_titles
    )
    print(
        "Recommendations are unique:",
        results["recommended_movie"].is_unique
    )
    display(results)

Number of recommendations: 5
Selected movie excluded: True
Recommendations are unique: True

                         recommended_movie  similarity_score
0                    The Dark Knight Rises            0.4447
1                           Batman Returns            0.3714
2                            Batman Begins            0.3372
3  Batman: The Dark Knight Returns, Part 2            0.2955
4                           Batman Forever            0.2881

In [28]:
test_movies = [
    "The Dark Knight",
    "Avatar",
    "Iron Man",
    "Titanic",
    "The Avengers"
]

for movie in test_movies:
    print(f"\nRecommendations for: {movie}")
    display(recommend_movies(movie, top_n=5))

Recommendations for: The Dark Knight

                         recommended_movie  similarity_score
0                    The Dark Knight Rises            0.4447
1                           Batman Returns            0.3714
2                            Batman Begins            0.3372
3  Batman: The Dark Knight Returns, Part 2            0.2955
4                           Batman Forever            0.2881

Recommendations for: Avatar

         recommended_movie  similarity_score
0                   Aliens            0.2047
1            Falcon Rising            0.2037
2      Battle: Los Angeles            0.1976
3                Apollo 18            0.1841
4  Star Trek Into Darkness            0.1713

Recommendations for: Iron Man

            recommended_movie  similarity_score
0                  Iron Man 2            0.4445
1                  Iron Man 3            0.3568
2     Avengers: Age of Ultron            0.3289
3                     Ant-Man            0.2210
4  Captain America: Civil War            0.2203

Recommendations for: Titanic

                             recommended_movie  similarity_score
0                                   Ghost Ship            0.2172
1                                     Poseidon            0.2070
2                      In the Heart of the Sea            0.1971
3  Pirates of the Caribbean: On Stranger Tides            0.1858
4                               The Black Hole            0.1838

Recommendations for: The Avengers

                    recommended_movie  similarity_score
0             Avengers: Age of Ultron            0.3151
1          Captain America: Civil War            0.2504
2  Captain America: The First Avenger            0.2353
3                          Iron Man 3            0.2250
4                            Iron Man            0.2149

In [29]:
def evaluate_recommendations(movie_titles, top_n=5):
    results = []

    for title in movie_titles:
        recommendations = recommend_movies(title, top_n=top_n)

        results.append({
            "input_movie": title,
            "recommendations_returned": len(recommendations),
            "no_self_recommendation": (
                title.lower() not in
                recommendations["recommended_movie"].str.lower().tolist()
            ) if not recommendations.empty else False,
            "unique_recommendations": (
                recommendations["recommended_movie"].is_unique
            ) if not recommendations.empty else False
        })

    return pd.DataFrame(results)


evaluation_results = evaluate_recommendations(test_movies)
display(evaluation_results)

,input_movie,recommendations_returned,no_self_recommendation,unique_recommendations
0,The Dark Knight,5,True,True
1,Avatar,5,True,True
2,Iron Man,5,True,True
3,Titanic,5,True,True
4,The Avengers,5,True,True